public class siva_account_handler {
    
  /**  public static void createopp(list<Account>acc){
       list<opportunity>op=new list<opportunity>();
        for(Account a : acc){
            if(a.NumberOfEmployees>99){
                for(integer i=0;i<10;i++){
                    opportunity o=new opportunity();
                    o.Name=a.Name;
                    o.StageName='closed won';
                    o.CloseDate=system.today()+20;
                    o.AccountId=a.Id;
                    op.add(o);
                }
                insert op;
            }
        }
    }   
    public static void identicalopportunity(list<Account> acc){
        list<opportunity>op=new list<opportunity>();
        for(Account a : acc){
            if(a.NumberOfEmployees>99){
                for(integer i=0;i<10;i++){
                    opportunity o=new opportunity();
                    o.Name=a.Name;
                    o.StageName='closed won';
                    o.CloseDate=system.today()+20;
                    o.AccountId=a.Id;
                    op.add(o);
                }
                insert op;
            }
        } **/
    }